version: '3.8'
services:
  org:
    container_name: connect-org-core
    image: ghcr.io/mrexmelle/connect-org:0.2.1
    environment:
      - APP_PROFILE=docked
    ports:
      - '8081:8081'
    networks:
      - connect_proxy_network

networks:
  connect_proxy_network:
      name: connect-network
      external: true
