version: '3.8'
services:
  core:
    container_name: connect-orgs-core
    image: ghcr.io/mrexmelle/connect-orgs:0.1.0
    environment:
      - APP_PROFILE=docked
    ports:
      - '8081:8081'
    networks:
      - connect_proxy_network

networks:
  connect_proxy_network:
      name: connect-network
      external: true
