app:
  datasource:
    read:
      host: postgres
      port: 5432
      user: orgs_r
      password: 123
      dbname: orgs
      sslmode: disable
      timezone: Asia/Jakarta
    write:
      host: postgres
      port: 5432
      user: orgs_w
      password: 123
      dbname: orgs
      sslmode: disable
      timezone: Asia/Jakarta
  server:
    port: 8081