app:
  datasource:
    read:
      host: postgres
      port: 5432
      user: org_r
      password: 123
      dbname: org
      sslmode: disable
      timezone: Asia/Jakarta
    write:
      host: postgres
      port: 5432
      user: org_w
      password: 123
      dbname: org
      sslmode: disable
      timezone: Asia/Jakarta
  server:
    port: 8081