app:
  datasource:
    read:
      host: 127.0.0.1
      port: 5432
      user: orgs_r
      password: 123
      dbname: orgs
      sslmode: disable
      timezone: Asia/Jakarta
    write:
      host: 127.0.0.1
      port: 5432
      user: orgs_w
      password: 123
      dbname: orgs
      sslmode: disable
      timezone: Asia/Jakarta
  server:
    port: 8081